# Generated by Django 4.2.1 on 2023-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privatechatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmessage',
            name='text_content',
            field=models.TextField(),
        ),
    ]
