# Generated by Django 4.2.1 on 2023-09-01 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0004_folder_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_code',
            field=models.CharField(default=0, max_length=16, verbose_name='文档邀请码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='guest_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='edited_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
