# Generated by Django 4.2.1 on 2023-09-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='edited_by',
        ),
        migrations.AlterField(
            model_name='page',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
