# Generated by Django 4.2.4 on 2023-08-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('photo_url', models.CharField(default='', max_length=128, verbose_name='用户头像路径')),
                ('photo_url_out', models.CharField(default='http://82.157.165.72:8888/photo/default.jpg', max_length=128, verbose_name='外部用户头像路径')),
                ('is_login', models.BooleanField(default=False, verbose_name='登录状态')),
            ],
        ),
    ]
