# Generated by Django 4.1.5 on 2023-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('role', models.CharField(choices=[('creator', '团队创建者'), ('admin', '团队管理员'), ('member', '普通成员')], max_length=10, verbose_name='职位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('photo_url', models.CharField(default='', max_length=128, verbose_name='用户头像路径')),
            ],
        ),
    ]
